# Generated by Django 5.0.6 on 2024-09-19 20:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolvisit',
            name='tool',
        ),
        migrations.AddField(
            model_name='toolvisit',
            name='tool_slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolvisit',
            name='visit_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='toolvisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='toolvisit',
            name='visit_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
