# Generated by Django 5.0.4 on 2024-05-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_image', models.ImageField(upload_to='images/ai-screenshot/')),
                ('ai_name', models.CharField(max_length=255)),
                ('ai_tool_logo', models.ImageField(upload_to='images/logos/')),
                ('ai_short_description', models.TextField()),
                ('ai_pricing_tag', models.CharField(max_length=255)),
                ('ai_tags', models.CharField(max_length=255)),
                ('ai_tool_link', models.URLField()),
            ],
        ),
    ]
