# Generated by Django 5.0.6 on 2024-05-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
