# Generated by Django 5.0.6 on 2024-05-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aitool_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitool',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
