# Generated by Django 4.2.3 on 2024-08-09 02:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_aitool_ai_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='ai_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/ai-screenshot/'),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='ai_pricing_tag',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='ai_tags',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='ai_tool_logo',
            field=models.ImageField(default='images/default_logo.jpg', upload_to='images/logos/'),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='aitool',
            index=models.Index(fields=['ai_name'], name='main_aitool_ai_name_494c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='aitool',
            index=models.Index(fields=['ai_pricing_tag'], name='main_aitool_ai_pric_32460f_idx'),
        ),
        migrations.AddIndex(
            model_name='aitool',
            index=models.Index(fields=['ai_tags'], name='main_aitool_ai_tags_86a91a_idx'),
        ),
        migrations.AddIndex(
            model_name='aitool',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='main_aitool_search__108900_gin'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='main_catego_name_5111b9_idx'),
        ),
    ]
