# Generated by Django 4.2.3 on 2024-08-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aitool_search_vector_alter_aitool_ai_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitool',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
