# Generated by Django 5.0.6 on 2024-08-12 05:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_aitool_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitool',
            name='ai_short_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
