# Generated by Django 5.0.6 on 2024-08-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_aitool_ai_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitool',
            name='ai_image',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/ai-screenshot/'),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='ai_tool_logo',
            field=models.ImageField(blank=True, default='images/default_logo.jpg', upload_to='images/logos/'),
        ),
    ]
