# Generated by Django 5.0.6 on 2024-08-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_rating_unique_together_remove_rating_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.toolcomment'),
        ),
    ]
