# Generated by Django 5.0.6 on 2024-08-23 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_toolcomment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='featured_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aitool',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='aitool',
            index=models.Index(fields=['is_featured', 'featured_order'], name='main_aitool_is_feat_bec743_idx'),
        ),
    ]
