# Generated by Django 5.0.6 on 2024-08-23 13:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_aitool_featured_order_aitool_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitool',
            name='ai_short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
